# Generated by Django 5.2.1 on 2026-04-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_in_days', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(default='info', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('average_turnaround_days', models.PositiveIntegerField(default=7)),
                ('accuracy_metric', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('due_in_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='action_required', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services_app.servicetype')),
            ],
        ),
    ]
