from django.urls import path

from apps.directory.views import (
    AdminCompanyTierAssignmentConfirmView,
    AdminCompanyTierAssignmentView,
    AdminCompanyTierDetailView,
    AdminCompanyTierRequestApproveView,
    AdminCompanyTierRequestListView,
    AdminCompanyTierRequestRejectView,
    AdminCompanyMarketVisibilityView,
    AdminCompanyTierListCreateView,
    AdminCompanyTierToggleView,
    AdminMarketPreviewView,
    AdminMarketReportSummaryView,
    AdminMarketRowDetailView,
    AdminMarketRowListCreateView,
    AdminMarketUnderServedReportView,
    AdminMarketZoneDetailView,
    AdminMarketZoneEligibilityRuleView,
    AdminMarketZoneListCreateView,
    AdminPlacementOverrideDetailView,
    AdminPlacementOverrideListCreateView,
)

from .views import (
    AdminCompanyProfilesView,
    AdminOverviewView,
    AssociationCreateView,
    DistrictUnitBulkCreateView,
    HierarchyManagementView,
    UnitBulkCreateView,
)

urlpatterns = [
    path("", AdminOverviewView.as_view(), name="admin_overview"),
    path("company-profiles/", AdminCompanyProfilesView.as_view(), name="admin_company_profiles"),
    path("hierarchy/", HierarchyManagementView.as_view(), name="admin_hierarchy"),
    path("directory/tiers/", AdminCompanyTierListCreateView.as_view(), name="admin_directory_tier_list_create"),
    path("directory/tiers/<int:tier_id>/", AdminCompanyTierDetailView.as_view(), name="admin_directory_tier_detail"),
    path("directory/tier-requests/", AdminCompanyTierRequestListView.as_view(), name="admin_directory_tier_request_list"),
    path("directory/tier-requests/<int:request_id>/approve/", AdminCompanyTierRequestApproveView.as_view(), name="admin_directory_tier_request_approve"),
    path("directory/tier-requests/<int:request_id>/reject/", AdminCompanyTierRequestRejectView.as_view(), name="admin_directory_tier_request_reject"),
    path("market-zones/", AdminMarketZoneListCreateView.as_view(), name="admin_market_zone_list_create"),
    path("market-zones/<int:zone_id>/", AdminMarketZoneDetailView.as_view(), name="admin_market_zone_detail"),
    path("market-zones/<int:zone_id>/eligibility-rules/", AdminMarketZoneEligibilityRuleView.as_view(), name="admin_market_zone_eligibility_rules"),
    path("market-rows/", AdminMarketRowListCreateView.as_view(), name="admin_market_row_list_create"),
    path("market-rows/<int:row_id>/", AdminMarketRowDetailView.as_view(), name="admin_market_row_detail"),
    path("placement-overrides/", AdminPlacementOverrideListCreateView.as_view(), name="admin_placement_override_list_create"),
    path("placement-overrides/<int:override_id>/", AdminPlacementOverrideDetailView.as_view(), name="admin_placement_override_detail"),
    path("market-preview/", AdminMarketPreviewView.as_view(), name="admin_market_preview"),
    path("market-report/summary/", AdminMarketReportSummaryView.as_view(), name="admin_market_report_summary"),
    path("market-report/under-served/", AdminMarketUnderServedReportView.as_view(), name="admin_market_report_under_served"),
    path(
        "directory/tiers/<int:tier_id>/<str:action>/",
        AdminCompanyTierToggleView.as_view(),
        name="admin_directory_tier_toggle",
    ),
    path("directory/companies/<int:company_id>/tier/", AdminCompanyTierAssignmentView.as_view(), name="admin_directory_company_tier_assign"),
    path(
        "directory/companies/<int:company_id>/market-visibility/",
        AdminCompanyMarketVisibilityView.as_view(),
        name="admin_directory_company_market_visibility",
    ),
    path(
        "directory/companies/<int:company_id>/tier/confirm/",
        AdminCompanyTierAssignmentConfirmView.as_view(),
        name="admin_directory_company_tier_confirm",
    ),
    path("associations/", AssociationCreateView.as_view(), name="admin_association_create"),
    path("district-units/bulk/", DistrictUnitBulkCreateView.as_view(), name="admin_district_unit_bulk_create"),
    path("units/bulk/", UnitBulkCreateView.as_view(), name="admin_unit_bulk_create"),
]
