from django.urls import path

from apps.accounts.access_views import (
    AssociationAdminAccessRequestApproveView,
    AssociationAdminAccessRequestListView,
    AssociationAdminAccessRequestRejectView,
    CompanyAdminAccessRequestApproveView,
    CompanyAdminAccessRequestListView,
    CompanyAdminAccessRequestRejectView,
)
from apps.directory.views import (
    AdminCompanyTierAssignmentConfirmView,
    AdminCompanyTierAssignmentView,
    AdminCompanyTierDetailView,
    AdminCompanyTierRequestApproveView,
    AdminCompanyTierRequestListView,
    AdminCompanyTierRequestRejectView,
    AdminCompanyMarketVisibilityView,
    AdminCompanyTierListCreateView,
    AdminCompanyTierToggleView,
    AdminMarketPreviewView,
    AdminMarketReportSummaryView,
    AdminMarketRowDetailView,
    AdminMarketRowListCreateView,
    AdminMarketScreenSettingsView,
    AdminMarketUnderServedReportView,
    AdminMarketZoneDetailView,
    AdminMarketZoneEligibilityRuleView,
    AdminMarketZoneListCreateView,
    AdminPlacementOverrideDetailView,
    AdminPlacementOverrideListCreateView,
    AdminProductAttributeDefinitionDetailView,
    AdminProductAttributeDefinitionListCreateView,
    AdminProductCategoryDetailView,
    AdminProductCategoryListCreateView,
    AdminProductSubCategoryDetailView,
    AdminProductSubCategoryListCreateView,
    AdminProductTaxonomyView,
)

from .views import (
    AdminCompanyProfilesView,
    AdminOverviewView,
    AssociationCreateView,
    DistrictUnitBulkCreateView,
    HierarchyManagementView,
    UnitBulkCreateView,
)

urlpatterns = [
    path("", AdminOverviewView.as_view(), name="admin_overview"),
    path("company-profiles/", AdminCompanyProfilesView.as_view(), name="admin_company_profiles"),
    path("hierarchy/", HierarchyManagementView.as_view(), name="admin_hierarchy"),
    path("access/company-admin-requests/", CompanyAdminAccessRequestListView.as_view(), name="admin_company_admin_access_request_list"),
    path(
        "access/company-admin-requests/<int:request_id>/approve/",
        CompanyAdminAccessRequestApproveView.as_view(),
        name="admin_company_admin_access_request_approve",
    ),
    path(
        "access/company-admin-requests/<int:request_id>/reject/",
        CompanyAdminAccessRequestRejectView.as_view(),
        name="admin_company_admin_access_request_reject",
    ),
    path(
        "access/association-admin-requests/",
        AssociationAdminAccessRequestListView.as_view(),
        name="admin_association_admin_access_request_list",
    ),
    path(
        "access/association-admin-requests/<int:request_id>/approve/",
        AssociationAdminAccessRequestApproveView.as_view(),
        name="admin_association_admin_access_request_approve",
    ),
    path(
        "access/association-admin-requests/<int:request_id>/reject/",
        AssociationAdminAccessRequestRejectView.as_view(),
        name="admin_association_admin_access_request_reject",
    ),
    path("directory/taxonomy/", AdminProductTaxonomyView.as_view(), name="admin_directory_taxonomy"),
    path("directory/taxonomy/categories/", AdminProductCategoryListCreateView.as_view(), name="admin_directory_taxonomy_category_list_create"),
    path(
        "directory/taxonomy/categories/<int:category_id>/",
        AdminProductCategoryDetailView.as_view(),
        name="admin_directory_taxonomy_category_detail",
    ),
    path(
        "directory/taxonomy/subcategories/",
        AdminProductSubCategoryListCreateView.as_view(),
        name="admin_directory_taxonomy_subcategory_list_create",
    ),
    path(
        "directory/taxonomy/subcategories/<int:subcategory_id>/",
        AdminProductSubCategoryDetailView.as_view(),
        name="admin_directory_taxonomy_subcategory_detail",
    ),
    path(
        "directory/taxonomy/attributes/",
        AdminProductAttributeDefinitionListCreateView.as_view(),
        name="admin_directory_taxonomy_attribute_list_create",
    ),
    path(
        "directory/taxonomy/attributes/<int:attribute_id>/",
        AdminProductAttributeDefinitionDetailView.as_view(),
        name="admin_directory_taxonomy_attribute_detail",
    ),
    path("directory/tiers/", AdminCompanyTierListCreateView.as_view(), name="admin_directory_tier_list_create"),
    path("directory/tiers/<int:tier_id>/", AdminCompanyTierDetailView.as_view(), name="admin_directory_tier_detail"),
    path("directory/tier-requests/", AdminCompanyTierRequestListView.as_view(), name="admin_directory_tier_request_list"),
    path("directory/tier-requests/<int:request_id>/approve/", AdminCompanyTierRequestApproveView.as_view(), name="admin_directory_tier_request_approve"),
    path("directory/tier-requests/<int:request_id>/reject/", AdminCompanyTierRequestRejectView.as_view(), name="admin_directory_tier_request_reject"),
    path("market-zones/", AdminMarketZoneListCreateView.as_view(), name="admin_market_zone_list_create"),
    path("market-zones/<int:zone_id>/", AdminMarketZoneDetailView.as_view(), name="admin_market_zone_detail"),
    path("market-zones/<int:zone_id>/eligibility-rules/", AdminMarketZoneEligibilityRuleView.as_view(), name="admin_market_zone_eligibility_rules"),
    path("market-rows/", AdminMarketRowListCreateView.as_view(), name="admin_market_row_list_create"),
    path("market-rows/<int:row_id>/", AdminMarketRowDetailView.as_view(), name="admin_market_row_detail"),
    path("placement-overrides/", AdminPlacementOverrideListCreateView.as_view(), name="admin_placement_override_list_create"),
    path("placement-overrides/<int:override_id>/", AdminPlacementOverrideDetailView.as_view(), name="admin_placement_override_detail"),
    path("market-preview/", AdminMarketPreviewView.as_view(), name="admin_market_preview"),
    path("market-screen-settings/", AdminMarketScreenSettingsView.as_view(), name="admin_market_screen_settings"),
    path("market-report/summary/", AdminMarketReportSummaryView.as_view(), name="admin_market_report_summary"),
    path("market-report/under-served/", AdminMarketUnderServedReportView.as_view(), name="admin_market_report_under_served"),
    path(
        "directory/tiers/<int:tier_id>/<str:action>/",
        AdminCompanyTierToggleView.as_view(),
        name="admin_directory_tier_toggle",
    ),
    path("directory/companies/<int:company_id>/tier/", AdminCompanyTierAssignmentView.as_view(), name="admin_directory_company_tier_assign"),
    path(
        "directory/companies/<int:company_id>/market-visibility/",
        AdminCompanyMarketVisibilityView.as_view(),
        name="admin_directory_company_market_visibility",
    ),
    path(
        "directory/companies/<int:company_id>/tier/confirm/",
        AdminCompanyTierAssignmentConfirmView.as_view(),
        name="admin_directory_company_tier_confirm",
    ),
    path("associations/", AssociationCreateView.as_view(), name="admin_association_create"),
    path("district-units/bulk/", DistrictUnitBulkCreateView.as_view(), name="admin_district_unit_bulk_create"),
    path("units/bulk/", UnitBulkCreateView.as_view(), name="admin_unit_bulk_create"),
]
