# Generated by Django 5.2.1 on 2026-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="public_url",
            field=models.URLField(blank=True),
        ),
    ]
