# Generated by Django 5.2.1 on 2026-04-28 20:15

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


INITIAL_TIERS = [
    {
        "name": "Prime Signature",
        "slug": "prime-signature",
        "description": "Top-tier featured placement for flagship companies.",
        "max_products": 50,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": 10,
        "price": "0.00",
        "is_free": False,
        "is_active": True,
        "display_priority": 10,
        "visibility_type": "featured",
    },
    {
        "name": "Prime Classic",
        "slug": "prime-classic",
        "description": "Featured placement for established companies with a smaller slot count.",
        "max_products": 25,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": 25,
        "price": "0.00",
        "is_free": False,
        "is_active": True,
        "display_priority": 20,
        "visibility_type": "featured",
    },
    {
        "name": "Prime Premier",
        "slug": "prime-premier",
        "description": "Priority pro listing for high-capacity suppliers.",
        "max_products": 15,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": 50,
        "price": "0.00",
        "is_free": False,
        "is_active": True,
        "display_priority": 30,
        "visibility_type": "pro",
    },
    {
        "name": "Prime Elite",
        "slug": "prime-elite",
        "description": "Mid-volume pro listing for focused product portfolios.",
        "max_products": 7,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": 75,
        "price": "0.00",
        "is_free": False,
        "is_active": True,
        "display_priority": 40,
        "visibility_type": "pro",
    },
    {
        "name": "Prime Circle",
        "slug": "prime-circle",
        "description": "Standard market listing for active directory members.",
        "max_products": 3,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": 100,
        "price": "0.00",
        "is_free": False,
        "is_active": True,
        "display_priority": 50,
        "visibility_type": "normal",
    },
    {
        "name": "Prime Unique",
        "slug": "prime-unique",
        "description": "Entry-level free listing with a single showcase product.",
        "max_products": 1,
        "min_photos_per_product": 3,
        "max_photos_per_product": 5,
        "max_companies_allowed": None,
        "price": "0.00",
        "is_free": True,
        "is_active": True,
        "display_priority": 60,
        "visibility_type": "normal",
    },
]


def seed_company_tiers_and_backfill(apps, schema_editor):
    CompanyTier = apps.get_model("directory", "CompanyTier")
    Company = apps.get_model("directory", "Company")

    tier_by_slug = {}
    for tier_spec in INITIAL_TIERS:
        tier, _ = CompanyTier.objects.get_or_create(
            slug=tier_spec["slug"],
            defaults=tier_spec,
        )
        tier_by_slug[tier_spec["slug"]] = tier

    mapping = {
        "premium": tier_by_slug["prime-signature"].id,
        "pro": tier_by_slug["prime-premier"].id,
        "normal": tier_by_slug["prime-circle"].id,
    }

    for company in Company.objects.all().iterator():
        company.tier_ref_id = mapping.get(company.tier, tier_by_slug["prime-circle"].id)
        company.save(update_fields=["tier_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_mediaasset_public_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("max_products", models.PositiveIntegerField()),
                ("min_photos_per_product", models.PositiveIntegerField(default=3)),
                ("max_photos_per_product", models.PositiveIntegerField(default=5)),
                ("max_companies_allowed", models.PositiveIntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_free", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_priority", models.PositiveIntegerField(default=0)),
                (
                    "visibility_type",
                    models.CharField(
                        choices=[("featured", "Featured"), ("pro", "Pro"), ("normal", "Normal")],
                        max_length=20,
                    ),
                ),
            ],
            options={"ordering": ["display_priority", "id"]},
        ),
        migrations.AddField(
            model_name="company",
            name="admin_priority",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="tier_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="companies", to="directory.companytier"),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_company_tiers_and_backfill, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="company",
            name="tier",
        ),
        migrations.AlterField(
            model_name="company",
            name="tier_ref",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="companies", to="directory.companytier"),
        ),
    ]
