# Generated by Django 5.2.1 on 2026-05-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_exposureledger_reporting_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTierChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('company_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('current_tier_name', models.CharField(max_length=120)),
                ('requested_tier_name', models.CharField(max_length=120)),
                ('retain_active_product_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_change_requests', to='directory.company')),
                ('current_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_tier_change_requests', to='directory.companytier')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tier_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tier_change_requests', to='directory.companytier')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tier_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
