# Generated by Django 5.2.1 on 2026-05-13 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_company_hierarchy_and_memberships(apps, schema_editor):
    Company = apps.get_model("directory", "Company")
    CompanyMembership = apps.get_model("directory", "CompanyMembership")
    MemberProfile = apps.get_model("accounts", "MemberProfile")
    UserRole = apps.get_model("accounts", "UserRole")
    RegionState = apps.get_model("regions", "RegionState")

    state_lookup = {}
    for state in RegionState.objects.all():
        state_lookup.setdefault((state.name or "").casefold(), []).append(state.id)

    profile_map = {}
    for profile in MemberProfile.objects.exclude(company_name="").select_related(
        "state",
        "association",
        "district_operational_unit",
        "unit",
    ):
        profile_map.setdefault(profile.company_name, []).append(profile)

    for company in Company.objects.all():
        update_fields = []
        profiles = profile_map.get(company.name, [])
        if company.state_ref_id is None and company.state:
            state_ids = state_lookup.get(company.state.casefold(), [])
            if len(state_ids) == 1:
                company.state_ref_id = state_ids[0]
                update_fields.append("state_ref")

        profile_state_ids = {profile.state_id for profile in profiles if profile.state_id}
        profile_association_ids = {profile.association_id for profile in profiles if profile.association_id}
        profile_district_ids = {profile.district_operational_unit_id for profile in profiles if profile.district_operational_unit_id}
        profile_unit_ids = {profile.unit_id for profile in profiles if profile.unit_id}

        if company.state_ref_id is None and len(profile_state_ids) == 1:
            company.state_ref_id = next(iter(profile_state_ids))
            update_fields.append("state_ref")
        if company.association_ref_id is None and len(profile_association_ids) == 1:
            company.association_ref_id = next(iter(profile_association_ids))
            update_fields.append("association_ref")
        if company.district_operational_unit_ref_id is None and len(profile_district_ids) == 1:
            company.district_operational_unit_ref_id = next(iter(profile_district_ids))
            update_fields.append("district_operational_unit_ref")
        if company.unit_ref_id is None and len(profile_unit_ids) == 1:
            company.unit_ref_id = next(iter(profile_unit_ids))
            update_fields.append("unit_ref")
        if not company.company_type:
            if company.association_ref_id:
                company.company_type = "association_linked"
                update_fields.append("company_type")
            elif company.state_ref_id:
                company.company_type = "independent"
                update_fields.append("company_type")
        if company.state_ref_id:
            resolved_state = RegionState.objects.filter(pk=company.state_ref_id).first()
            if resolved_state is not None and company.state != resolved_state.name:
                company.state = resolved_state.name
                update_fields.append("state")
        if update_fields:
            company.save(update_fields=sorted(set(update_fields)))

    primary_company_ids = set()
    for user_role in UserRole.objects.filter(role="company_admin", scope_type="company").order_by("scope_id", "id"):
        if not user_role.scope_id:
            continue
        company = Company.objects.filter(pk=user_role.scope_id).first()
        if company is None:
            continue
        existing_primary = CompanyMembership.objects.filter(
            company_id=company.id,
            status="active",
            is_primary_admin=True,
        ).exists()
        is_primary_admin = company.id not in primary_company_ids and not existing_primary
        membership, created = CompanyMembership.objects.get_or_create(
            user_id=user_role.user_id,
            company_id=company.id,
            defaults={
                "role": "primary_admin" if is_primary_admin else "admin",
                "status": "active",
                "is_primary_admin": is_primary_admin,
                "approved_at": user_role.created_at,
            },
        )
        if created and is_primary_admin:
            primary_company_ids.add(company.id)
        elif not created and membership.status != "active":
            membership.status = "active"
            membership.save(update_fields=["status", "updated_at"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference_product_alerts_and_notifications'),
        ('directory', '0015_companynotificationsubscription'),
        ('regions', '0003_remove_legacy_region_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='association_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='regions.association'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('independent', 'Independent'), ('association_linked', 'Association Linked')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='district_operational_unit_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='regions.districtoperationalunit'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='regions.regionstate'),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='regions.unit'),
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary_admin', 'Primary Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='admin', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=20)),
                ('is_primary_admin', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_company_memberships', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='directory.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uniq_company_membership_user_company'), models.UniqueConstraint(condition=models.Q(('is_primary_admin', True), ('status', 'active')), fields=('company',), name='uniq_active_primary_company_admin')],
            },
        ),
        migrations.RunPython(backfill_company_hierarchy_and_memberships, noop_reverse),
    ]
