# Generated by Django 5.2.1 on 2026-04-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reach', models.CharField(default='local', max_length=50)),
                ('status', models.CharField(default='pending_review', max_length=50)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdTargeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('district_name', models.CharField(blank=True, max_length=100)),
                ('local_chapter_name', models.CharField(blank=True, max_length=100)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targeting', to='ads.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='AdAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(default='dashboard_hero', max_length=100)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_asset', to='directory.mediaasset')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ads.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='AdApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='ads.advertisement')),
            ],
        ),
    ]
