# Generated by Django 5.2.1 on 2026-04-27 13:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_ad_targeting(apps, schema_editor):
    AdTargeting = apps.get_model('ads', 'AdTargeting')
    RegionState = apps.get_model('regions', 'RegionState')
    Association = apps.get_model('regions', 'Association')
    DistrictOperationalUnit = apps.get_model('regions', 'DistrictOperationalUnit')
    Unit = apps.get_model('regions', 'Unit')

    for targeting in AdTargeting.objects.all():
        state = RegionState.objects.filter(name=targeting.state_name).order_by('id').first() if targeting.state_name else None
        association = None
        district_operational_unit = None
        unit = None

        if targeting.local_chapter_name:
            unit_matches = list(Unit.objects.filter(name=targeting.local_chapter_name).order_by('id')[:2])
            if len(unit_matches) == 1:
                unit = unit_matches[0]
                district_operational_unit = unit.district_operational_unit
                association = district_operational_unit.association
                state = association.state

        if unit is None and targeting.district_name:
            district_matches = list(DistrictOperationalUnit.objects.filter(name=targeting.district_name).order_by('id')[:2])
            if len(district_matches) == 1:
                district_operational_unit = district_matches[0]
                association = district_operational_unit.association
                state = association.state

        if association is None and state is not None:
            association_matches = list(Association.objects.filter(state=state).order_by('id')[:2])
            if len(association_matches) == 1:
                association = association_matches[0]

        targeting.state = state
        targeting.association = association
        targeting.district_operational_unit = district_operational_unit
        targeting.unit = unit
        targeting.save(update_fields=['state', 'association', 'district_operational_unit', 'unit'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('regions', '0002_alter_regiondistrict_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtargeting',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_targetings', to='regions.association'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='district_operational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_targetings', to='regions.districtoperationalunit'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_targetings', to='regions.regionstate'),
        ),
        migrations.AddField(
            model_name='adtargeting',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_targetings', to='regions.unit'),
        ),
        migrations.RunPython(backfill_ad_targeting, noop_reverse),
    ]
