# Generated by Django 5.2.1 on 2026-04-28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_advertisement_fields(apps, schema_editor):
    Advertisement = apps.get_model("ads", "Advertisement")
    AdApproval = apps.get_model("ads", "AdApproval")
    AdAsset = apps.get_model("ads", "AdAsset")

    for advertisement in Advertisement.objects.all():
        approval = AdApproval.objects.filter(advertisement=advertisement).first()
        first_asset = AdAsset.objects.filter(advertisement=advertisement).order_by("id").first()
        update_fields = []

        if not advertisement.label_text:
            advertisement.label_text = "ADVERTISEMENT"
            update_fields.append("label_text")
        if not advertisement.placement:
            advertisement.placement = getattr(first_asset, "placement", "dashboard_hero") or "dashboard_hero"
            update_fields.append("placement")
        if not advertisement.action_type:
            advertisement.action_type = "external_url"
            update_fields.append("action_type")
        if advertisement.action_payload is None:
            advertisement.action_payload = {}
            update_fields.append("action_payload")
        if approval and advertisement.approved_by_id != approval.approved_by_id:
            advertisement.approved_by_id = approval.approved_by_id
            update_fields.append("approved_by")
        if approval and advertisement.approved_at != approval.approved_at:
            advertisement.approved_at = approval.approved_at
            update_fields.append("approved_at")
        if update_fields:
            advertisement.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("ads", "0003_remove_legacy_adtargeting_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={"ordering": ["-priority", "-created_at"]},
        ),
        migrations.AddField(
            model_name="advertisement",
            name="action_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("external_url", "External URL"),
                    ("internal_screen", "Internal Screen"),
                    ("product", "Product"),
                    ("company", "Company"),
                    ("category", "Category"),
                ],
                default="external_url",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="background_color",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertisement",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="label_text",
            field=models.CharField(default="ADVERTISEMENT", max_length=50),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="placement",
            field=models.CharField(
                choices=[
                    ("dashboard_hero", "Dashboard Hero"),
                    ("market_banner", "Market Banner"),
                    ("news_inline", "News Inline"),
                ],
                default="dashboard_hero",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_advertisement_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="advertisement",
            name="ends_at",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="starts_at",
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_id", models.CharField(blank=True, max_length=255, null=True)),
                ("placement", models.CharField(max_length=50)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("advertisement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="impressions", to="ads.advertisement")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-viewed_at", "-id"]},
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_id", models.CharField(blank=True, max_length=255, null=True)),
                ("placement", models.CharField(max_length=50)),
                ("action_type", models.CharField(max_length=50)),
                ("action_payload", models.JSONField(blank=True, default=dict)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                ("advertisement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clicks", to="ads.advertisement")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-clicked_at", "-id"]},
        ),
    ]
