# Generated by Django 5.2.1 on 2026-05-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_system_v1'),
        ('directory', '0010_exposureledger_reporting_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='directory.company'),
        ),
    ]
