# Generated by Django 5.2.1 on 2026-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_label', models.CharField(max_length=120)),
                ('gold_22k', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_24k', models.DecimalField(decimal_places=2, max_digits=10)),
                ('silver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalMarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('region_label', models.CharField(max_length=100)),
                ('gold_22k', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_24k', models.DecimalField(decimal_places=2, max_digits=10)),
                ('silver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_oz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('silver_oz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
