# Generated by Django 5.2.1 on 2026-04-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
        ('regions', '0003_remove_legacy_region_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationrate',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='regions.association'),
        ),
    ]
