# Generated by Django 5.2.1 on 2026-05-08 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_associationrate_association'),
        ('regions', '0003_remove_legacy_region_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('unit_label', models.CharField(default='1 Gram', max_length=60)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_rate_categories', to='regions.association')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rate_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssociationRateSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('unit_label', models.CharField(default='1 Gram', max_length=60)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='rates.associationratecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rate_subcategories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='associationratecategory',
            constraint=models.UniqueConstraint(fields=('association', 'slug'), name='uniq_rate_category_per_association_slug'),
        ),
        migrations.AddConstraint(
            model_name='associationratesubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_rate_subcategory_per_category_slug'),
        ),
    ]
