# Generated by Django 5.2.1 on 2026-04-27 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_member_profiles(apps, schema_editor):
    MemberProfile = apps.get_model('accounts', 'MemberProfile')
    RegionState = apps.get_model('regions', 'RegionState')
    Association = apps.get_model('regions', 'Association')
    DistrictOperationalUnit = apps.get_model('regions', 'DistrictOperationalUnit')
    Unit = apps.get_model('regions', 'Unit')

    for profile in MemberProfile.objects.all():
        state = RegionState.objects.filter(name=profile.state_name).order_by('id').first() if profile.state_name else None
        association = None
        district_operational_unit = None
        unit = None

        if profile.local_chapter_name:
            unit_matches = list(Unit.objects.filter(name=profile.local_chapter_name).order_by('id')[:2])
            if len(unit_matches) == 1:
                unit = unit_matches[0]
                district_operational_unit = unit.district_operational_unit
                association = district_operational_unit.association
                state = association.state

        if unit is None and profile.district_name:
            district_matches = list(DistrictOperationalUnit.objects.filter(name=profile.district_name).order_by('id')[:2])
            if len(district_matches) == 1:
                district_operational_unit = district_matches[0]
                association = district_operational_unit.association
                state = association.state

        if association is None and state is not None:
            association_matches = list(Association.objects.filter(state=state).order_by('id')[:2])
            if len(association_matches) == 1:
                association = association_matches[0]

        profile.state = state
        profile.association = association
        profile.district_operational_unit = district_operational_unit
        profile.unit = unit
        profile.save(update_fields=['state', 'association', 'district_operational_unit', 'unit'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('regions', '0002_alter_regiondistrict_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='regions.association'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='district_operational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='regions.districtoperationalunit'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='regions.regionstate'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='regions.unit'),
        ),
        migrations.CreateModel(
            name='AdminScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='regions.association')),
                ('district_operational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='regions.districtoperationalunit')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='regions.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_member_profiles, noop_reverse),
    ]
