# Generated by Django 5.2.1 on 2026-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_legacy_memberprofile_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('guest', 'Guest'), ('member', 'Member'), ('supplier', 'Supplier'), ('advertiser', 'Advertiser'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
