# Generated by Django 5.2.1 on 2026-04-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('regions', '0003_remove_legacy_region_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_access_requests', to='regions.association')),
                ('district_operational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_access_requests', to='regions.districtoperationalunit')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_access_requests', to='regions.regionstate')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_access_requests', to='regions.unit')),
            ],
        ),
    ]
