# Generated by Django 5.2.1 on 2026-04-28 18:40

import django.db.models.deletion
from django.db import migrations, models


def backfill_user_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    UserRole = apps.get_model("accounts", "UserRole")
    AdminScopeAssignment = apps.get_model("accounts", "AdminScopeAssignment")

    for user in User.objects.filter(role="super_admin"):
        UserRole.objects.get_or_create(
            user_id=user.id,
            role="super_admin",
            scope_type="platform",
            scope_id=None,
        )

    for assignment in AdminScopeAssignment.objects.all():
        if assignment.association_id:
            role = "association_admin"
            scope_type = "association"
            scope_id = assignment.association_id
        elif assignment.district_operational_unit_id:
            role = "district_admin"
            scope_type = "district_operational_unit"
            scope_id = assignment.district_operational_unit_id
        elif assignment.unit_id:
            role = "unit_admin"
            scope_type = "unit"
            scope_id = assignment.unit_id
        else:
            continue

        UserRole.objects.get_or_create(
            user_id=assignment.user_id,
            role=role,
            scope_type=scope_type,
            scope_id=scope_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_memberaccessrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("state_admin", "State Admin"),
                            ("association_admin", "Association Admin"),
                            ("district_admin", "District Admin"),
                            ("unit_admin", "Unit Admin"),
                            ("company_admin", "Company Admin"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("state", "State"),
                            ("association", "Association"),
                            ("district_operational_unit", "District Operational Unit"),
                            ("unit", "Unit"),
                            ("company", "Company"),
                        ],
                        max_length=40,
                    ),
                ),
                ("scope_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scoped_roles", to="accounts.user"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "scope_type", "scope_id"),
                        name="uniq_user_role_scope_assignment",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_user_roles, migrations.RunPython.noop),
    ]
