# Generated by Django 5.2.1 on 2026-05-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="product_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("product", "Product"), ("news", "News"), ("meeting", "Meeting"), ("rate", "Rate")], max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("target_route", models.CharField(choices=[("ProductDetail", "Product Detail"), ("NewsDetail", "News Detail"), ("MeetingDetail", "Meeting Detail"), ("RateDetails", "Rate Details")], max_length=40)),
                ("target_payload", models.JSONField(blank=True, default=dict)),
                ("source_object_type", models.CharField(max_length=30)),
                ("source_object_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["type", "created_at"], name="acct_notif_type_created_ix"),
                    models.Index(fields=["source_object_type", "source_object_id"], name="acct_notif_source_ix"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="accounts.notification")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="accounts.user")),
            ],
            options={
                "ordering": ["-notification__created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="acct_usernotif_user_read_ix"),
                    models.Index(fields=["created_at"], name="acct_usernotif_created_ix"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "notification"), name="uniq_user_notification"),
                ],
            },
        ),
    ]
