# Generated by Django 5.2.1 on 2026-05-13 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference_product_alerts_and_notifications'),
        ('directory', '0015_companynotificationsubscription'),
        ('regions', '0003_remove_legacy_region_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('access_approval', 'Access Approval')], default='access_approval', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activation_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssociationAdminAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requested_role', models.CharField(choices=[('state_admin', 'State Admin'), ('association_admin', 'Association Admin'), ('district_admin', 'District Admin'), ('unit_admin', 'Unit Admin')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_owner_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('association_admin', 'Association Admin'), ('district_admin', 'District Admin')], max_length=30)),
                ('approval_owner_scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_association_admin_access_requests', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_admin_access_requests', to='regions.association')),
                ('district_operational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_admin_access_requests', to='regions.districtoperationalunit')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_association_admin_access_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_association_admin_access_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_association_admin_access_requests', to='accounts.userrole')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_admin_access_requests', to='regions.regionstate')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_admin_access_requests', to='regions.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAdminAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=120)),
                ('company_type', models.CharField(choices=[('independent', 'Independent'), ('association_linked', 'Association Linked')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_owner_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('association_admin', 'Association Admin')], max_length=30)),
                ('approval_owner_scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_company_admin_access_requests', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_access_requests', to='regions.association')),
                ('district_operational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_access_requests', to='regions.districtoperationalunit')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_company_admin_access_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_company_admin_access_requests', to='directory.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
