# Generated by Django 5.2.1 on 2026-05-13 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountactivationtoken_associationadminaccessrequest_and_more'),
        ('directory', '0016_company_association_ref_company_company_type_and_more'),
        ('regions', '0003_remove_legacy_region_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadminaccessrequest',
            name='resolved_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_company_admin_access_requests', to='directory.companymembership'),
        ),
        migrations.AddField(
            model_name='companyadminaccessrequest',
            name='resolved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_company_admin_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyadminaccessrequest',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_access_requests', to='regions.regionstate'),
        ),
        migrations.AddField(
            model_name='companyadminaccessrequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_access_requests', to='regions.unit'),
        ),
    ]
