# Generated by Django 5.2.1 on 2026-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_companyadminaccessrequest_resolved_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_auth_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_google_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
