# Generated by Django 5.2.1 on 2026-04-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='regions.regionstate')),
            ],
            options={
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DistrictOperationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_units', to='regions.association')),
            ],
            options={
                'unique_together': {('association', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district_operational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='regions.districtoperationalunit')),
            ],
            options={
                'unique_together': {('district_operational_unit', 'name')},
            },
        ),
    ]
